### ISSUE TITLE
Error reporting in T4 templates in Linq2Db

### ISSUE THREAD

**Issue by ijsgaus** [JetBrains/ForTea#12]
This templates worked fine in Visual Studio, but produced errors in Rider IDE.
![Rider_T4_Linq2Db](https://user-images.githubusercontent.com/15998152/69459158-312a8080-0d82-11ea-9f28-8f4c2bdaec37.png)

**Comment by ijsgaus** [comment]
When Run in Rider produce error:
[Error] Unresolved include: LinqToDB.Tools.ttinclude

**Comment by kirillgla** [comment]
Could you provide more details, please? How exactly was `LinqToDB.Tools.ttinclude` included when it produced the error?

**Comment by kirillgla** [comment]
As for `MultipleFiles.ttinclude`, that's a known issue, EnvDTE is indeed not supported yet. Please, feel free to upvote this issue: https://youtrack.jetbrains.com/issue/RIDER-35770

**Comment by kirillgla** [comment]
This functionality was indeed broken. Thank you for your report! The fix is now merged into the branch net193 and will be available in the next EAP of Rider

**Comment by integral-llc** [comment]
was this fixed? I have the latest Rider 
```
JetBrains Rider 2020.1.3
Build #RD-201.7846.1, built on May 15, 2020
```
but the issue still persists.

**Comment by kirillgla** [comment]
I believe it was. Could you also tell me the version of the T4 plugin installed in your instance of Rider, please? It can be found in settings:
![image](https://user-images.githubusercontent.com/31822295/84073584-c832ef00-a9d9-11ea-873a-37fa33378d0b.png)

**Comment by integral-llc** [comment]
I have this
[cid:image001.png@01D63DA7.94803030]

Do I need to subscribe to EAP channel for Rider?

**Comment by integral-llc** [comment]
![image](https://user-images.githubusercontent.com/1841073/84103098-f9ee8a80-a9c6-11ea-85bc-76a8f6935b78.png)
here it is again.

**Comment by kirillgla** [comment]
Thank you for reporting that! We will investigate this issue

**Comment by alejandrod** [comment]
Same where! Plugin 2020.2.284

**Comment by pavelvondrasek** [comment]
still not working :( I'm using eap 2020.3

**Comment by kirillgla** [comment]
@integral-llc, @alejandrod and @pavelvondrasek, thanks for your reports! I've checked that the red code only appears in files that are not included into any of your T4 files. For instance, in this example `Linq2DB.ttinclude` is indirectly included into `Template.tt` and hence has no errors, while `NotifyDataErrorInfo.ttinclude` is not included into `Template.ttinclude` and hence contains the red code.

Is that the case in your projects, or do you experience red code in files that are included into T4 files that compile and run correctly?

![image](https://user-images.githubusercontent.com/31822295/99317230-c61d6800-2876-11eb-8d20-ce0436dee10a.png)

**Comment by pavelvondrasek** [comment]
I'm not using T4 templates (and I don't know how it should work) but it was annoying for me that I only install my favourite database layer and see all red... 

So that I cannot help you with answer I fixed it with removing linq2db.postgresql and added npgsql directly (how guys from linq2db recommended me) 😀

**Comment by kirillgla** [comment]
You saw all red after installing templates because linq2db includes are not self-sufficient. Some templates contain references to assemblies, other templates contain usages of symbols from these assemblies, so without a template that includes those ttincludes it is impossible to resolve symbols from them. I'll think about what we can do about that

**Comment by picolino** [comment]
Upvote for it. It is pain to see red errors across all project tree because of not self-sufficiency linq2db

**Comment by kirillgla** [comment]
Thank you everyone for your patience! Unfortunately, due to the way those templates are written, there isn't much we can do about it on Rider side. This problem has to be solved on linq2db side. I created [an issue](https://github.com/linq2db/linq2db/issues/2633) there, so please feel free to upvote that
