### ISSUE TITLE
Assembly references are not resolved when project/file is opened for the first time

### ISSUE THREAD

**Issue by liviuu** [JetBrains/ForTea#30]
I've noticed this problem after upgrading to R# 2020.1
Visual Studio 2019 Professional 16.5.4

```
<#@ template debug="false" hostspecific="true" language="C#" inherits="MyCustomBaseClass"#>
<#@ output extension=".sql" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="$(SolutionDir)Dependencies\MyDependency.dll" #>
```
I have a base class for the template defined in assembly MyDependency.dll

When I first open de TT file, Intellisense is not available and MyCustomBaseClass is red.

If I touch the assembly name attribute and add/remove a space
I presume this modification triggers an update of references, and Intellisense is miraculously restored.

Once restored, the assembly is found for the duration of the Visual Studio instance.
When I restart Visual Studio I have to do this trick again.

**Comment by kirillgla** [comment]
Thank you for the report!
I think I fixed this issue. The fix will be publicly available with the release of R# 2020.3. If you want to try it right away, [here's](https://github.com/JetBrains/ForTea/files/4982584/JetBrains.ForTea.2020.2.0.3.nupkg.zip) a plugin with the fix that is compatible with R# 2020.2 EAP8.
As always any feedback on whether or not this solved your problem is welcome. 😄
